const INSPECTOR_TEXT_KEYS = {
  "Add": "styles.add",
  "Remove": "styles.remove",
  "Close": "styles.close",
  "Apply class": "styles.applyClass",
  "Clear override, restore class value": "styles.restoreClassValue",
  "Restore class value": "styles.restoreClassValue",
  "Layout": "styles.layout",
  "Appearance": "styles.appearance",
  "Background": "styles.background",
  "Border": "styles.border",
  "Outline": "styles.outline",
  "Padding": "styles.padding",
  "Margin": "styles.margin",
  "Radius": "styles.radius",
  "Scale": "styles.scale",
  "Typography": "styles.typography",
  "Position": "styles.position",
  "Pinning": "styles.pinning",
  "Styles": "styles.styles",
  "Props": "styles.props",
  "Code": "styles.code",
  "Alignment": "styles.alignment",
  "Blend mode": "styles.blendMode",
  "Dimensions": "styles.dimensions",
  "Flow": "styles.flow",
  "Gap": "styles.gap",
  "Opacity": "styles.opacity",
  "Opacity %": "styles.opacityPercent",
  "Width": "styles.width",
  "Height": "styles.height",
  "Size": "styles.size",
  "Weight": "styles.weight",
  "Type": "styles.type",
  "Color": "styles.color",
  "Color value": "styles.colorValue",
  "Color format": "styles.colorFormat",
  "Image URL": "styles.imageUrl",
  "Overflow": "styles.overflow",
  "Position type": "styles.positionType",
  "Position alignment": "styles.positionAlignment",
  "Horizontal constraint": "styles.horizontalConstraint",
  "Vertical constraint": "styles.verticalConstraint",
  "Text alignment": "styles.textAlignment",
  "Vertical alignment": "styles.verticalAlignment",
  "Text formatting": "styles.textFormatting",
  "Font": "styles.font",
  "Font family": "styles.fontFamily",
  "Font weight": "styles.fontWeight",
  "Letter spacing": "styles.letterSpacing",
  "Letter-spacing Tailwind classes": "styles.letterSpacingClasses",
  "Line height": "styles.lineHeight",
  "Blur": "styles.blur",
  "Offset": "styles.offset",
  "Spread": "styles.spread",
  "Shadow color": "styles.shadowColor",
  "Shadow type": "styles.shadowType",
  "Outline color": "styles.outlineColor",
  "Filter type": "styles.filterType",
  "Gradient type": "styles.gradientType",
  "Repeat": "styles.repeat",
  "Resize": "styles.resize",
  "Rotation": "styles.rotation",
  "Rotate 90°": "styles.rotate90",
  "Flip horizontal": "styles.flipHorizontal",
  "Flip vertical": "styles.flipVertical",
  "Align left": "styles.alignLeft",
  "Align right": "styles.alignRight",
  "Align top": "styles.alignTop",
  "Align bottom": "styles.alignBottom",
  "Center horizontally": "styles.centerHorizontally",
  "Center vertically": "styles.centerVertically",
  "More arrangement options": "styles.moreArrangement",
  "Lock aspect ratio": "styles.lockAspectRatio",
  "Unlock aspect ratio": "styles.unlockAspectRatio",
  "Clip Content": "styles.clipContent",
  "Scroll Content": "styles.scrollContent",
  "Show Overflow": "styles.showOverflow",
  "Normal": "styles.normal",
  "Static": "styles.static",
  "Relative": "styles.relative",
  "Absolute": "styles.absolute",
  "Fixed": "styles.fixed",
  "Sticky": "styles.sticky",
  "Auto": "styles.auto",
  "Size fields": "styles.sizeFields",
  "Shadow properties": "styles.shadowProperties",
  "All Fonts": "styles.allFonts",
  "Recent": "styles.recent",
  "No repeat": "styles.noRepeat",
  "Repeat X": "styles.repeatX",
  "Repeat Y": "styles.repeatY",
  "Contain": "styles.contain",
  "Cover": "styles.cover",
  "Fill": "styles.fill",
  "Solid": "styles.solid",
  "Gradient": "styles.gradient",
  "Image": "styles.image",
  "Linear": "styles.linear",
  "Radial": "styles.radial",
  "Angular": "styles.angular",
  "Block": "styles.block",
  "Grid": "styles.grid",
  "Flex Row": "styles.flexRow",
  "Flex Column": "styles.flexColumn",
  "Hug": "styles.hug",
  "Top": "styles.top",
  "Right": "styles.right",
  "Bottom": "styles.bottom",
  "Left": "styles.left",
  "Center": "styles.center",
  "Top left": "styles.topLeft",
  "Top right": "styles.topRight",
  "Bottom left": "styles.bottomLeft",
  "Bottom right": "styles.bottomRight",
  "Left & Right": "styles.leftRight",
  "Top & Bottom": "styles.topBottom",
  "Space between": "styles.spaceBetween",
  "Space around": "styles.spaceAround",
  "Space evenly": "styles.spaceEvenly",
  "All": "styles.all",
  "Backdrop": "styles.backdrop",
  "Box Shadow": "styles.boxShadow",
  "Drop Shadow": "styles.dropShadow",
  "Inner Shadow": "styles.innerShadow",
  "Sans": "styles.sans",
  "Serif": "styles.serif",
  "Mono": "styles.mono",
  "Max Width": "styles.maxWidth",
  "Max Height": "styles.maxHeight",
  "Min Width": "styles.minWidth",
  "Min Height": "styles.minHeight",
  "Search fonts...": "styles.searchFonts",
  "Search classes...": "styles.searchClasses",
  "Or paste image URL…": "styles.pasteImageUrl",
  "Add fill": "styles.addFill",
  "Remove fill": "styles.removeFill",
  "Add filter": "styles.addFilter",
  "Add outline": "styles.addOutline",
  "Add scale": "styles.addScale",
  "Add shadow": "styles.addShadow",
  "Add stop": "styles.addStop",
  "Remove stop": "styles.removeStop",
  "Sample color": "styles.sampleColor",
  "Link a color token": "styles.linkColorToken",
  "Unlink class": "styles.unlinkClass",
  "Close font picker": "styles.closeFontPicker",
  "Close shadow editor": "styles.closeShadowEditor",
  "Drag to reorder": "styles.dragToReorder",
  "Shadow": "styles.shadow",
  "Mixed": "styles.mixed",
  "Value": "styles.value",
  "Show": "styles.show",
  "Hide": "styles.hide",
  "Wrap items": "styles.wrapItems",
  "Disable wrapping": "styles.disableWrapping",
  "Link sides": "styles.linkSides",
  "Separate sides": "styles.separateSides",
  "Border side": "styles.borderSide",
  "Apply border class": "styles.applyBorderClass",
  "All border sides added": "styles.allBorderSidesAdded",
  "Add border": "styles.addBorder",
  "Scale factor": "styles.scaleFactor",
  "Scaled width": "styles.scaledWidth",
  "Scaled height": "styles.scaledHeight",
  "Align center": "styles.alignCenter",
  "Align middle": "styles.alignMiddle",
  "Multiply": "styles.multiply",
  "Screen": "styles.screen",
  "Overlay": "styles.overlay",
  "Darken": "styles.darken",
  "Lighten": "styles.lighten",
  "Color Dodge": "styles.colorDodge",
  "Color Burn": "styles.colorBurn",
  "Hard Light": "styles.hardLight",
  "Soft Light": "styles.softLight",
  "Difference": "styles.difference",
  "Exclusion": "styles.exclusion",
  "Hue": "styles.hue",
  "Saturation": "styles.saturation",
  "Luminosity": "styles.luminosity",
  "Plus Darker": "styles.plusDarker",
  "Plus Lighter": "styles.plusLighter",
} as const;

function translateInspectorText(t, value) {
  if (typeof value !== "string") return value;
  const key = INSPECTOR_TEXT_KEYS[value];
  return key ? t(key) : value;
}

export { translateInspectorText };
