const PROJECT_CONFIGURATION_SCHEMA_VERSION = 2;
const PROJECT_CONFIGURATION_RELATIVE_PATH = ".bingo/config.json";
const PROJECT_CONFIGURATION_STORAGE_MODES = ["project", "app"];
const PROJECT_CONFIGURATION_GIT_PREFERENCES = ["unchanged", "ignore", "not-applicable"];

export {
  PROJECT_CONFIGURATION_GIT_PREFERENCES,
  PROJECT_CONFIGURATION_RELATIVE_PATH,
  PROJECT_CONFIGURATION_SCHEMA_VERSION,
  PROJECT_CONFIGURATION_STORAGE_MODES,
};
