export { ProjectActivityProvider, acquireProjectRender, waitForProjectRenderReady } from "./shared/lib/projectActivity";
/*
 * Reconstructed barrel: the original was tree-shaken out of the bundle,
 * since a module that only re-exports emits no code. Rebuilt from the
 * symbols the rest of the tree imports from this package. See RECOVERY.md.
 */
export { BingoLogo } from "./assets/BingoLogo";
export { BackendProvider, useBackend, useBackendOptional } from "./backends/BackendContext";
export { isPlanLimitError, isPlanLimitReason, planLimitTitle } from "./backends/planLimits";
export { AgentFollowFrame } from "./canvas/components/AgentFollowFrame";
export { Canvas } from "./canvas/components/Canvas";
export { CanvasLayout } from "./canvas/components/CanvasLayout";
export { AiLockOverlays, HoverOverlay, ROOT_LABEL_MIN_SCALE, RootLabels, SelectionOverlay, useOverlayGeoms } from "./canvas/components/CanvasOverlays";
export { CanvasPixelGrid } from "./canvas/components/CanvasPixelGrid";
export { CanvasToolbar } from "./canvas/components/CanvasToolbar";
export { CanvasZoomMenu } from "./canvas/components/CanvasZoomMenu";
export { CapturedPageRenderer } from "./canvas/components/CapturedPageRenderer";
export { CommentPins } from "./canvas/components/CommentPins";
export { ComponentEditingModeBar } from "./canvas/components/ComponentEditingModeBar";
export { DraggableElement } from "./canvas/components/DraggableElement";
export { ElementErrorBoundary } from "./canvas/components/ErrorBoundary";
export { MediaUploadPlaceholder } from "./canvas/components/MediaUploadPlaceholder";
export { MediaWithFallback } from "./canvas/components/MediaWithFallback";
export { SplitButton } from "./canvas/components/SplitButton";
export { TextEditor } from "./canvas/components/TextEditor";
export { WebviewRenderer } from "./canvas/components/WebviewRenderer";
export { findContainerAt } from "./canvas/hooks/drawParent";
export { useCanvasDraw } from "./canvas/hooks/useCanvasDraw";
export { useCanvasMarquee } from "./canvas/hooks/useCanvasMarquee";
export { useCanvasPersistence } from "./canvas/hooks/useCanvasPersistence";
export { useDndCanvas } from "./canvas/hooks/useDndCanvas";
export { usePotentialParentOverlay } from "./canvas/hooks/usePotentialParentOverlay";
export { useResizing } from "./canvas/hooks/useResizing";
export { captureCanvasPreview } from "./canvas/lib/canvasPreview";
export { CAPTURE_ARTIFACT } from "./canvas/lib/capture/artifact.generated";
export { getAttrs$2 } from "./canvas/lib/capture/attrs";
export { BLOCK_TAGS, CAPTURE_ATTRS, CSS_DEFAULTS$1, INHERITED_PROPS, PASSTHROUGH_TAGS, REPLACED, SKIP_ATTR_PREFIXES, SKIP_DEFAULT_VALUES, SKIP_PROPS, SKIP_TAGS$1, VOID_ELEMENTS$1 } from "./canvas/lib/capture/constants";
export { authoredChildrenKind, detectIconName, detectProjectRoot, extractComponentProps, findAncestorCompositeByName, findContainingComponent, findImmediateComposite, findOwningComponent, getComponentName, getFiber, isLiveSafeComponent, pickKnownComponentName, registryNameFromDataSlot, registryNameFromBingoAttr, resolveAsChildOwner, resolveSourceInfoBatch, stripPropSynthesizedChildren } from "./canvas/lib/capture/fiber";
export { runCapture } from "./canvas/lib/capture/runCapture";
export { applyStyleHeuristics, extractInlineStyles, getStyles, stripAuthoredLayout, stripCanvasInvalidPosition, stripKeywordSizes } from "./canvas/lib/capture/styles";
export { getUtilityAuthoredValue, hasAuthoredProp, preloadSheets } from "./canvas/lib/capture/stylesheets";
export { captureSvg } from "./canvas/lib/capture/svg";
export { createIdGen, walkChildren, walkNode } from "./canvas/lib/capture/walk";
export { copyToFigma } from "./canvas/lib/figmaExport";
export { applyFonts, cleanupFonts } from "./canvas/lib/fontUtils";
export { OUT_OF_FLOW_STYLE_KEYS, computeAbsoluteOffsetStyles, isFlowLayoutDisplay, isRelativeFlowPosition, positionStylesForParent } from "./canvas/utils/absolutePositioning";
export { canAdoptElement } from "./canvas/utils/adoptionGuard";
export { readCanvasElements } from "./canvas/utils/canvasPayload";
export { captureComponentInstance, clearComponentEditSession, editSessionFromElement, findEditRootId$1, findEditSessionsInStore, getComponentEditSession, isComponentEditRoot, isInsideComponentEdit, rendersThroughWebgl, stashComponentEditSession } from "./canvas/utils/captureComponentInstance";
export { applyFlexReorderPreview, canvasElementFromPoint, clearFlexReorderPreview, createFlexSlotCache, getCanvasRect, getElementComputedMargins, getElementRect$1, getFlexDropSlot, isCompletelyOutside, isFullyInside, isPointerWithinFlexParentCrossAxis } from "./canvas/utils/collisionUtils";
export { yieldsToCoveredRoot } from "./canvas/utils/coveredRoot";
export { computeEdgeDistances, getAbsoluteContainingBox, getCanvasSpaceRect, getElementPaddingBox, isFlowLayoutElement } from "./canvas/utils/domGeometry";
export { mapScreenPoint, previewZoomDrift, screenToCanvas } from "./canvas/utils/dragFrame";
export { dragPreviewBoxSize, readDragPreviewGeometry, withDragPreviewSize } from "./canvas/utils/dragPreviewGeometry";
export { captureFromIframe, captureFromWebview, detectRepoRootFromCapture, getTargetFingerprint, markWebviewArtifactStale } from "./canvas/utils/fiberExtract";
export { applyFigmaImagePatchesToStore } from "./canvas/utils/figma";
export { cameraToFitRect } from "./canvas/utils/fitCamera";
export { cameraToFitFollowRect, componentNamesForWritePath, followRectForTarget, followTargetIds, instanceIdsForComponentNames, isOutermostLock, liveCanvasComponentNames, unionFollowRects } from "./canvas/utils/followAiCamera";
export { companionGeometry } from "./canvas/utils/multiResize";
export { movesDeeper, resolveNestTarget, shouldReturnToFlow } from "./canvas/utils/nestTarget";
export { resolvePointerTarget } from "./canvas/utils/pointerTarget";
export { collectAdoptedChildren, countGridColumns$1, isContainedWithin, orderAdoptedChildren, renderElement } from "./canvas/utils/renderElement";
export { countClick, isDescendClick, resolveDescendTarget, sameSelection } from "./canvas/utils/selection";
export { NO_SNAP_MEMORY, collectSnapLines, computeResizeSnap, computeSnap, computeSpacing, visibleSnapRects } from "./canvas/utils/snapping";
export { IDENTITY_LINEAR, accumulatedLinearTransform, accumulatedLinearTransformString, invertLinear, linearFromTransform, multiplyLinear, relativeTranslationMatrix, transformLinearMatrix } from "./canvas/utils/transformMatrix";
export { CANVAS_ZOOM_STEP, MIN_CANVAS_SCALE, cameraToFit, clampCanvasScale, zoomAtCenter, zoomScaleForWheel } from "./canvas/utils/zoom";
export { ActiveToolProvider, isInsertTool, useActiveTool } from "./shared/contexts/ActiveToolContext";
export { AssetProvider, useAssetResolver } from "./shared/contexts/AssetContext";
export { EditorModeProvider, useEditorMode } from "./shared/contexts/EditorModeContext";
export { useUploadImage } from "./shared/hooks/useUploadImage";
export { readCamera, writeCamera } from "./shared/lib/cameraStore";
export { getRememberedRoot, setRememberedRoot } from "./shared/lib/projectRootStore";
export { GLOBAL_SHORTCUTS, LOCAL_SHORTCUTS } from "./shared/shortcuts/catalog";
export { isCodeEditorTarget, isTypingTarget, matchesShortcut } from "./shared/shortcuts/matchShortcut";
export { useGlobalShortcut } from "./shared/shortcuts/useGlobalShortcut";
export { getAiWriteTarget, publishAiWriteTarget } from "./shared/state/aiWriteTarget";
export { getPixelGridEnabled, setPixelGridEnabled, subscribePixelGridEnabled } from "./shared/state/canvasDisplayPreferences";
export { publishFolderShared, subscribeFolderShared } from "./shared/state/folderShared";
export { publishHover, subscribeHover } from "./shared/state/hoverChannel";
export { useWebviewEditState, webviewEditStore } from "./shared/state/webviewEditStore";
export { captureElementImage, resolveCaptureElement } from "./shared/utils/captureElementImage";
export { clearLog, describeOperation, ensureLog, getOperations, popOperation, recordOperation, squashOperations, startLog, useOperationLog } from "./shared/utils/captureStore";
export { COMPOSITION_DRAG_MIME, copyElementToClipboard, createCompositionDragPayload, createImageElement, createVideoElement, fileToUrl, getImageFromDropEvent, getPendingPanelDragElement, htmlToJsx, isCanvasInsertDrag, isCanvasInsertDragType, looksLikeHTML, readElementFromClipboard, setCompositionDragData, setElementDragData } from "./shared/utils/clipboard";
export { hasAncestorIn, planDropMoves, resolveDropTarget, resolveLayerTreeDrop } from "./shared/utils/dropPlan";
export { cloneElementWithNewIds, regenerateTreeIds } from "./shared/utils/elementCloning";
export { expandLinkedMapOps } from "./shared/utils/expandLinkedMapOps";
export { normalizeFlexShrinkOps } from "./shared/utils/flexShrink";
export { normalizeFlowLayoutChildrenOps } from "./shared/utils/flowLayoutChildren";
export { buildFrameAdoptionOps, frameSlotAmongAdoptees } from "./shared/utils/frameAdoptionOps";
export { generatePrefixedId } from "./shared/utils/idUtils";
export { applyOperationsToStore, createInsertOperation, createMoveOperation, createRemoveOperation, createReplaceOperation, createSetNameOperation, createSetPositionOperation, createSetPropsOperation, createSetStylesOperation, createSetTextOperation, invertOperations } from "./shared/utils/operations";
export { groupElementsByTarget, resolveMultiPasteTargets } from "./shared/utils/pasteTargets";
export { alignCanvasSelection, distributeCanvasSelection, pinnedAlignmentStyles, positionedAlignmentStyles } from "./shared/utils/positionAlignment";
export { planSelectionReorder } from "./shared/utils/reorderSelection";
export { applyScalePivot, removeScalePivot, scaleResetCanvasOffset } from "./shared/utils/scalePivot";
export { getTransformScales, hasScaleAnchorTransform, multiplyTransformScale, removeScaleAnchorTransform, removeTransformScale, scaleFactorForDrag, scaleTransformAtHandle, scaleTransformAtPoint } from "./shared/utils/scaleTransform";
export { BORDER_TAILWIND_CATEGORIES, getAllTailwindColors, getAllTailwindEffects, getTailwindCategory, parseTailwindClass, smartMergeClasses } from "./shared/utils/tailwindScale";
export { CONTAINER_BG, DEFAULT_TOOL_SIZE, createToolElement, isDrawableTool } from "./shared/utils/toolElements";
export { parseTransformControls, topEdgeOfRotatedBox, withTransformFlips, withTransformRotation } from "./shared/utils/transformControls";
export { ScrubSessionContext, useColorPickerSession, useScrub } from "./shared/utils/useScrub";
export { hasMultiRootContents, measureVisibleBounds, resolveObservedElements, resolveVisibleElement$1 } from "./shared/utils/visibleElement";
export { ChatArchiveView } from "./shell/components/ArchivedChatsPanel";
export { BottomBar } from "./shell/components/BottomBar";
export { CanvasContextChip } from "./shell/components/CanvasContextChip";
export { ContextChip, ContextMenu, EffortPicker, FolderChip, ModelPicker, pickFolder } from "./shell/components/ChatContextControls";
export { ChatConversations } from "./shell/components/ChatConversations";
export { ChatActivityIndicator, ChatListRow } from "./shell/components/ChatListRow";
export { ChatMarkdown } from "./shell/components/ChatMarkdown";
export { ChatPanel, IMPORT_DESIGN_SYSTEM_PROMPT } from "./shell/components/ChatPanel";
export { ChatReferenceChip } from "./shell/components/ChatReferenceChip";
export { ChatTitleText } from "./shell/components/ChatTitleText";
export { ClaudeCodeSetupModal } from "./shell/components/ClaudeCodeSetupModal";
export { CommentComposer } from "./shell/components/CommentComposer";
export { CommentThread } from "./shell/components/CommentThread";
export { ComposerSuggestionGroup, ComposerSuggestionItem, ComposerSuggestionMenu } from "./shell/components/ComposerSuggestionMenu";
export { ConfirmDialog } from "./shell/components/ConfirmDialog";
export { ContextMentionMenu } from "./shell/components/ContextMentionMenu";
export { CreateComponentModal } from "./shell/components/CreateComponentModal";
export { EditableChatTitle } from "./shell/components/EditableChatTitle";
export { EditorStatusBar } from "./shell/components/EditorStatusBar";
export { FigmaConnectDialog } from "./shell/components/FigmaConnectDialog";
export { GitPanel } from "./shell/components/GitPanel";
export { HeaderActions } from "./shell/components/HeaderActions";
export { ImageContextChip } from "./shell/components/ImageContextChip";
export { InsertItem } from "./shell/components/InsertItem";
export { LeftSidebarV2 } from "./shell/components/LeftSidebarV2";
export { BingoEditor } from "./shell/components/BingoEditor";
export { useMcpConnect } from "./shell/components/McpConnectButton";
export { McpConnectModal } from "./shell/components/McpConnectModal";
export { PreviewWindow } from "./shell/components/PreviewWindow";
export { AIChatSettings } from "./shell/components/ProjectSettingsModal/AIChatSettings";
export { GeneralSettings } from "./shell/components/ProjectSettingsModal/GeneralSettings";
export { IconsSettings } from "./shell/components/ProjectSettingsModal/IconsSettings";
export { ProjectSettingsModal } from "./shell/components/ProjectSettingsModal/ProjectSettingsModal";
export { SettingRow } from "./shell/components/ProjectSettingsModal/SettingRow";
export { ProtoPlayer } from "./shell/components/ProtoPlayer";
export { SelectionContextChip } from "./shell/components/SelectionContextChip";
export { SIDEBAR_LIST_ROW_ACTIVE_CLASS, SIDEBAR_LIST_ROW_CLASS, SidebarSectionHeader } from "./shell/components/SidebarSectionHeader";
export { SlashCommandMenu } from "./shell/components/SlashCommandMenu";
export { ToolFailureDetails } from "./shell/components/ToolFailureDetails";
export { VersionHistoryModal } from "./shell/components/VersionHistoryModal";
export { AgentsSidebarTabV2 } from "./shell/components/panels/AgentsSidebarTabV2";
export { AssetsPanel, buildPreviewComponentProps, buildRequiredComponentProps, inventPropValue } from "./shell/components/panels/AssetsPanel";
export { AssetsSidebarTabV2 } from "./shell/components/panels/AssetsSidebarTabV2";
export { IconsPanel } from "./shell/components/panels/IconsPanel";
export { InsertPanel } from "./shell/components/panels/InsertPanel";
export { LayerIcon } from "./shell/components/panels/LayerIcon";
export { LayersPanel } from "./shell/components/panels/LayersPanel";
export { PagePanel, getPagesPanelSizes } from "./shell/components/panels/PagePanel";
export { PagesLayersSplit } from "./shell/components/panels/PagesLayersSplit";
export { PagesPanel } from "./shell/components/panels/PagesPanel";
export { PagesSidebarTabV2 } from "./shell/components/panels/PagesSidebarTabV2";
export { PanelEmptyState } from "./shell/components/panels/PanelEmptyState";
export { PanelSearchInput } from "./shell/components/panels/PanelSearchInput";
export { ElementHeader, PropsPanel } from "./shell/components/panels/PropsPanel";
export { SkillsPanel } from "./shell/components/panels/SkillsPanel";
export { StylesPanelTabs } from "./shell/components/panels/StylesPanelTabs";
export { DARK_TERMINAL_THEME, LIGHT_TERMINAL_THEME, TerminalPanel } from "./shell/components/panels/TerminalPanel";
export { WebviewEditPanel } from "./shell/components/panels/WebviewEditPanel";
export { CompositionPreview, collectCompositionPreviewNames, getCompositionParseContext, getCompositionParseSignature, parseCompositionImports, parseCompositionRootsByExport } from "./shell/components/panels/compositionDrag";
export { getLayerAccent, getLayerIcon } from "./shell/components/panels/layerAppearance";
export { getLayerLayoutIcon } from "./shell/components/panels/layerLayoutIcon";
export { createLayerSearchIndex, getElementLabel, splitLabelMatches, withTextParents } from "./shell/components/panels/layerSearch";
export { PropField, PropRow, handlePropInputKeyDown } from "./shell/components/panels/props/PropField";
export { InspectorToggleGroup } from "./shell/components/panels/styles/InspectorToggleGroup";
export { StyleOpsContext, useStyleField, useStyleOps } from "./shell/components/panels/styles/StyleOpsContext";
export { StyleColorInput } from "./shell/components/panels/styles/fields/color";
export { StyleInlineInput, StyleSectionField, StyleSectionRow, StyleToggleGroupField } from "./shell/components/panels/styles/fields/controls";
export { StyleDimensionInput, StyleLayoutInput, StyleLayoutMinMaxInput, StyleOpacityInput, StylePositionOffset } from "./shell/components/panels/styles/fields/layout";
export { StyleLetterSpacingInput } from "./shell/components/panels/styles/fields/typography";
export { ClassPickerContent } from "./shell/components/panels/styles/inputs/ClassPickerContent";
export { ColorPickerPopover } from "./shell/components/panels/styles/inputs/ColorPickerPopover";
export { ColorRow } from "./shell/components/panels/styles/inputs/ColorRow";
export { DimensionInput } from "./shell/components/panels/styles/inputs/DimensionInput";
export { GradientEditor } from "./shell/components/panels/styles/inputs/GradientEditor";
export { InlineInput } from "./shell/components/panels/styles/inputs/InlineInput";
export { LayoutMinMaxInput } from "./shell/components/panels/styles/inputs/LayoutMinMaxInput";
export { LayoutValueInput } from "./shell/components/panels/styles/inputs/LayoutValueInput";
export { SolidColorPicker } from "./shell/components/panels/styles/inputs/SolidColorPicker";
export { UnitMenu } from "./shell/components/panels/styles/inputs/UnitMenu";
export { ActiveClassChip, ActiveClassUnlinkAction } from "./shell/components/panels/styles/inputs/parts/ActiveClassChip";
export { ClassPickerPopover } from "./shell/components/panels/styles/inputs/parts/ClassPickerPopover";
export { InspectorDropdown } from "./shell/components/panels/styles/inputs/parts/InspectorDropdown";
export { OverrideChip } from "./shell/components/panels/styles/inputs/parts/OverrideChip";
export { useInspectorScrub } from "./shell/components/panels/styles/inputs/useInspectorScrub";
export { useUnitValue } from "./shell/components/panels/styles/inputs/useUnitValue";
export { FlexMainAxisGapInput, FlowToggleGroup, LinkSidesButton, LinkedSidesGrid, VisibilityToggleButton, WrapToggleButton } from "./shell/components/panels/styles/layout/controls";
export { FLEX_DISTRIBUTIONS, asFlexDistribution } from "./shell/components/panels/styles/layout/flexDistribution";
export { AlignmentCellGlyph, DistributedItemLine, FlexAlignmentGlyph, FlexColumnGlyph, FlexRowGlyph, FlexWrapGlyph, HexDotGlyph } from "./shell/components/panels/styles/layout/glyphs";
export { PositionSection } from "./shell/components/panels/styles/positioning/PositionSection";
export { PositionAlignmentControls, PositionConstraintsControl, PositionOffsetField, PositionPinningIcon, RotationField } from "./shell/components/panels/styles/positioning/widgets";
export { INSPECTOR_CONTROL_TEXT_STYLE, IconBtn, InspectorClassPickerIndicator, InspectorControlAction, InspectorControlInput, InspectorControlShell, InspectorDraggableRow, InspectorRailRow, InspectorScrubHandle, LayoutAddButton, LayoutFieldLabel, SourceChip, blurInspectorInputOnEnter, inspectorControlHeight, inspectorControlRadius, releaseInspectorControlFocus, styleFieldLabel } from "./shell/components/panels/styles/primitives";
export { AppearanceSection } from "./shell/components/panels/styles/sections/AppearanceSection";
export { BackgroundSection, TokenRow } from "./shell/components/panels/styles/sections/BackgroundSection";
export { BorderSection } from "./shell/components/panels/styles/sections/BorderSection";
export { FiltersSection } from "./shell/components/panels/styles/sections/FiltersSection";
export { InspectorSection } from "./shell/components/panels/styles/sections/InspectorSection";
export { MarginSection } from "./shell/components/panels/styles/sections/MarginSection";
export { OutlineSection } from "./shell/components/panels/styles/sections/OutlineSection";
export { PaddingSection } from "./shell/components/panels/styles/sections/PaddingSection";
export { RadiusSection } from "./shell/components/panels/styles/sections/RadiusSection";
export { ScaleSection } from "./shell/components/panels/styles/sections/ScaleSection";
export { ShadowSection } from "./shell/components/panels/styles/sections/ShadowSection";
export { TypographySection } from "./shell/components/panels/styles/sections/TypographySection";
export { CSSTab } from "./shell/components/panels/styles/tabs/CSSTab";
export { ClassesTab } from "./shell/components/panels/styles/tabs/ClassesTab";
export { CodeView } from "./shell/components/panels/styles/tabs/CodeView";
export { DesignTab } from "./shell/components/panels/styles/tabs/DesignTab";
export { FontFamilyPicker, FontWeightPicker } from "./shell/components/panels/styles/typography/FontPickers";
export { TextFormatRow } from "./shell/components/panels/styles/typography/TextFormatRow";
export { PresentationFrame, useFitToWidth, useFrameContent, useFramePager } from "./shell/components/presentation";
export { ARROW_KEYS, BORDER_KEYS, BORDER_STYLES, CHAT_COLORS, EFFECT_DEFS, EMPTY_STORE, MARGIN_KEYS, PADDING_KEYS, POSITION_LABELS, POSITION_TYPES, RADIUS_KEYS, TEXT_RUN_STYLE_KEYS, TEXT_STYLE_KEYS, TYPOGRAPHY_KEYS } from "./shell/constants";
export { dropPreviewRoots, insertNestedWithPaint, replacePreviewRoot, sanitizeDrawStreamId } from "./shell/hooks/canvasDrawStream";
export { UNKNOWN_ROOT_WIDTH, estimateUnmeasuredRootBox, nextRootPlacement } from "./shell/hooks/nextRootPlacement";
export { isDrawPreviewId, measuredRootBounds, occupiedRootBoxes, rootContentSettled, rootOccupancyBox } from "./shell/hooks/rootBoxes";
export { useBackendActions } from "./shell/hooks/useBackendActions";
export { useCanvasToolHandler } from "./shell/hooks/useCanvasToolHandler";
export { useChatScroll } from "./shell/hooks/useChatScroll";
export { useClassSuggestions, useClassesForProperty } from "./shell/hooks/useClassSuggestions";
export { BINGO_COMMANDS, buildConnectionPrompt, connectionDisplayName, fetchClaudeConnections, fetchSlashCommands, filterSlashCommands } from "./shell/hooks/useClaudeContext";
export { isClaudeSetUp, useClaudeStatus } from "./shell/hooks/useClaudeStatus";
export { useContextMentions } from "./shell/hooks/useContextMentions";
export { isHumanCanvasCommit, useTabHistory } from "./shell/hooks/useHistory";
export { useMixedLocalValue } from "./shell/hooks/useMixedLocalValue";
export { usePromptContextInsertion } from "./shell/hooks/usePromptContextInsertion";
export { useScrolledHeader } from "./shell/hooks/useScrolledHeader";
export { useSelectionJsxEditor } from "./shell/hooks/useSelectionJsxEditor";
export { MIXED } from "./shell/types";
export { isEmptyImage, parseFills, serializeFills } from "./shell/utils/backgroundFills";
export { CHAT_ATTACHMENT_ACCEPT, getDroppedAttachments, readPromptAttachment } from "./shell/utils/chatAttachments";
export { getContextOptions, projectReferenceLine, readContextToken } from "./shell/utils/chatContextReferences";
export { getChatDeletionQueue } from "./shell/utils/chatDeletion";
export { ChatPersistence } from "./shell/utils/chatPersistence";
export { driveCamera, getCamera, getCameraScale, isAddToPromptShortcut, isCameraDriving, notifyUserCameraGesture, publishCamera, registerCameraDriver, sameCamera, subscribeCamera, subscribeCameraScale, subscribeUserCameraGesture } from "./shell/utils/chatShortcuts";
export { CHAT_TITLE_ANIMATION, getTitleAnimationFrame } from "./shell/utils/chatTitleAnimation";
export { toolFailureReport } from "./shell/utils/chatToolFailure";
export { chatWorkTargets, lastChatWorkTarget, outermostChatWorkIds } from "./shell/utils/chatWorkTarget";
export { getClassIndex, getClassIndexGeneration, getClassesForProperty, isClassInCompiledStyles, searchClasses, subscribeClassIndex } from "./shell/utils/classIndex";
export { CODE_EDITOR_CLASS, CODE_EDITOR_THEME, useCodeEditorFontStyles } from "./shell/utils/codeEditorTheme";
export { alphaPct, buildColor, canvasColorToParts, clamp$1, colorToHex, colorToHex6, colorToHsva, colorToParts, hslToRgb, hsvaToHex, hsvaToRgba, hueHex, parseColorParts, parseColorToRgba, rgbHex6, rgbaToHsl, rgbaToHsva, sameColor, setAlphaOn, toHex6 } from "./shell/utils/colorMath";
export { camelToKebab, getCascadeBatch, kebabToCamel } from "./shell/utils/computedStyles";
export { displayValue, formatLetterSpacing, letterSpacingInputToCss, opacityInputValue, parseLetterSpacing } from "./shell/utils/cssValue";
export { EditorFileBreadcrumb, buildFileBreadcrumbItems } from "./shell/utils/editorBreadcrumb";
export { FILTER_DEFINITIONS, FILTER_KINDS, normalizeFilterAmount, parseFilterValues, parseShadowValues, replaceFilterFunctions, serializeBoxShadows, serializeFilterValue, serializeFilters, serializeShadowValue } from "./shell/utils/effectValues";
export { classifyEffect } from "./shell/utils/effects";
export { defaultGradient, isTransparentColor, parseFill, serializeFill, splitTopLevel$1 } from "./shell/utils/fillValue";
export { collectFontFamilies, ensureFontPreviews, ensureFontsLoaded } from "./shell/utils/fontLoader";
export { createElementFromTag, htmlTags } from "./shell/utils/htmlTagsData";
export { extractIconNames, searchIcons } from "./shell/utils/iconUtils";
export { InlineChatComposer, inlineChatPrompt, splitInlineChatReferences, syncInlineReferenceSpacing } from "./shell/utils/inlineChatComposer";
export { getMergedValue, isMixed } from "./shell/utils/multiSelect";
export { normalizeTextRuns } from "./shell/utils/normalizeTextRuns";
export { buildClassPropertyMap, computeCleanedStyles, pasteHasResolvingClasses } from "./shell/utils/pasteClassStyles";
export { usePropertyResolution } from "./shell/utils/styleResolution";
export { isInlineTypographyEdit, isTypographyClass } from "./shell/utils/tailwindClasses";
export { formatFontWeight, getFontDisplayName, getFontWeightMenuValues, getLocalFontWeights, isBoldFontWeight, parseFontWeight } from "./shell/utils/typography";
export { INSPECTOR_LENGTH_UNITS, commitInspectorUnitValue, getInspectorUnitInputValue, getInspectorUnitNumericValue, getInspectorUnitSelection, inspectorPropertySupportsAuto, parseInspectorUnitValue } from "./shell/utils/unitValue";
export { LUCIDE_PROPS_SCHEMA, PHOSPHOR_PROPS_SCHEMA } from "./types/components";

export { useLocalAgents } from "./shell/hooks/useLocalAgents";
